name: Custom Windows Client Generator
run-name: Custom Windows Client Generator
on: 
  workflow_dispatch:
    inputs:
      server:
        description: 'Rendezvous Server'
        required: true
        default: ''
        type: string
      key:
        description: 'Public Key'
        required: true
        default: ''
        type: string
      apiServer:
        description: 'API Server'
        required: true
        default: ''
        type: string
      custom:
        description: "Custom JSON"
        required: true
        default: ''
        type: string
      uuid:
        description: "uuid of request"
        required: true
        default: ''
        type: string
      iconlink:
        description: "icon link"
        required: false
        default: 'false'
        type: string
      logolink:
        description: "logo link"
        required: false
        default: 'false'
        type: string
      appname:
        description: "app name"
        required: true
        default: 'rustdesk'
        type: string
      filename:
        description: "Filename"
        required: true
        default: 'rustdesk'
        type: string
      extras:
        description: "extra inputs in json"
        required: true
        default: '{}'
        type: string

env:
  SCITER_RUST_VERSION: "1.75"
  RUST_VERSION: "1.75"
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"
  # Commit d'Avril 2023 (Stable pour RustDesk)
  VCPKG_COMMIT_ID: "501db0f17ef6df184fcdbfbe0f87cde2313b6ab1"
  VERSION: "${{ fromJson(inputs.extras).version }}"
  UPLOAD_ARTIFACT: 'true'

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml
    with:
      version: ${{ fromJson(inputs.extras).version }}

  build-RustDeskTempTopMostWindow:
    uses: ./.github/workflows/third-party-RustDeskTempTopMostWindow.yml
    with:
      upload-artifact: true
      target: windows-2022
      configuration: Release
      platform: x64
      target_version: Windows10
    secrets: inherit

  build-for-windows-flutter:
    name: Build Windows
    needs: [build-RustDeskTempTopMostWindow, generate-bridge]
    runs-on: windows-2022
    env:
      SIGN_BASE_URL: ${{ secrets.SIGN_BASE_URL }}
      SIGN_API_KEY: ${{ secrets.SIGN_API_KEY }}
      STATUS_URL: ${{ inputs.apiServer }}/api/updategh
      
    steps:
      - name: install python deps
        run: pip install requests pyzipper

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: rustdesk/rustdesk
          ref: ${{ env.VERSION == 'master' && 'master' || format('refs/tags/{0}', env.VERSION) }}
          submodules: recursive

      - name: Set API Status URL
        run: |
          if ("${{ fromJson(inputs.extras).rdgen }}" -eq "false") {
            echo "STATUS_URL=${{ inputs.apiServer }}/api/updategh" >> $env:GITHUB_ENV
          } else {
            echo "STATUS_URL=${{ secrets.GENURL }}/updategh" >> $env:GITHUB_ENV
          }

      - name: Install Build Tools
        run: |
          choco install -y nasm yasm ninja imagemagick.app --no-progress
          echo "C:\Program Files\NASM" >> $env:GITHUB_PATH

      # --- PERSONNALISATION ---
      - name: Apply patches and custom branding
        shell: bash
        run: |
          # Fix Base64
          sed -i '1i use hbb_common::base64::Engine;' ./src/hbbs_http/sync.rs
          sed -i 's/hbb_common::base64::encode/hbb_common::base64::engine::general_purpose::STANDARD.encode/g' ./src/hbbs_http/sync.rs
          
          # Branding
          sed -i -e 's|description = "RustDesk Remote Desktop"|description = "${{ inputs.appname }}"|' ./Cargo.toml
          sed -i -e 's|Purslane Ltd|${{ fromJson(inputs.extras).compname }}|g' ./Cargo.toml
          
          # Config
          sed -i -e 's|rs-ny.rustdesk.com|${{ inputs.server }}|' ./libs/hbb_common/src/config.rs
          sed -i -e 's|OeVuKk5nlHiXp+APNn0Y3pC1Iwpwn44JGqrQCsWqmBw=|${{ inputs.key }}|' ./libs/hbb_common/src/config.rs
          sed -i -e 's|https://admin.rustdesk.com|${{ inputs.apiServer }}|' ./src/common.rs
          sed -i -e 's|https://rustdesk.com|${{ fromJson(inputs.extras).urlLink }}|g' ./build.py

      - name: Process logo and icons
        if: ${{ inputs.iconlink != 'false' }}
        continue-on-error: true
        shell: pwsh
        run: |
          if (!(Test-Path "./res")) { New-Item -ItemType Directory -Path "./res" -Force }
          Invoke-WebRequest -Uri "${{ fromJson(inputs.iconlink).url }}/get_png?filename=${{ fromJson(inputs.iconlink).file }}&uuid=${{ fromJson(inputs.iconlink).uuid }}" -OutFile ./res/temp_raw.png
          
          magick ./res/temp_raw.png -strip -background none -alpha set -define png:color-type=6 -resize 256x256 ./res/icon.png
          magick ./res/icon.png -define icon:auto-resize=256,64,48,32,16 ./res/icon.ico
          cp ./res/icon.ico ./res/tray-icon.ico

      # --- VCPKG SETUP ---
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      # --- INSTALLATION DEPENDANCES (LIBMFX RETIRÃ‰) ---
      - name: Install Dependencies
        shell: pwsh
        run: |
          # 1. Suppression brutale de vcpkg.json
          Write-Host "Recherche et suppression de vcpkg.json..."
          Get-ChildItem -Path . -Filter "vcpkg.json" -Recurse | Remove-Item -Force -Verbose
          
          # 2. Installation SANS libmfx qui causait l'erreur
          & "$env:VCPKG_ROOT\vcpkg" install ffmpeg opus libvpx libyuv aom protobuf x264 --triplet x64-windows-static --x-install-root="$env:VCPKG_ROOT\installed"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.SCITER_RUST_VERSION }}
          targets: x86_64-pc-windows-msvc
          components: rustfmt

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      # --- COMPILATION ---
      - name: Build rustdesk
        shell: pwsh
        run: |
          python3 .\build.py --portable --hwcodec --flutter --vram --skip-portable-pack
          
          if (Test-Path "./rustdesk") { Remove-Item -Recurse -Force "./rustdesk" }
          mv ./flutter/build/windows/x64/runner/Release ./rustdesk

          Invoke-WebRequest -Uri https://github.com/rustdesk-org/rdev/releases/download/usbmmidd_v2/usbmmidd_v2.zip -OutFile usbmmidd_v2.zip
          Expand-Archive usbmmidd_v2.zip -DestinationPath . -Force
          Remove-Item -Path usbmmidd_v2\Win32, usbmmidd_v2\deviceinstaller64.exe, usbmmidd_v2\deviceinstaller.exe, usbmmidd_v2\usbmmidd.bat -Recurse -ErrorAction SilentlyContinue
          mv -Force .\usbmmidd_v2 ./rustdesk

          try {
            Invoke-WebRequest -Uri https://github.com/rustdesk/hbb_common/releases/download/driver/rustdesk_printer_driver_v4-1.4.zip -OutFile rustdesk_printer_driver_v4-1.4.zip
            Invoke-WebRequest -Uri https://github.com/rustdesk/hbb_common/releases/download/driver/printer_driver_adapter.zip -OutFile printer_driver_adapter.zip
            
            Expand-Archive rustdesk_printer_driver_v4-1.4.zip -DestinationPath . -Force
            if (!(Test-Path "./rustdesk/drivers/RustDeskPrinterDriver")) { New-Item -ItemType Directory -Path "./rustdesk/drivers/RustDeskPrinterDriver" -Force }
            mv -Force .\rustdesk_printer_driver_v4-1.4\* ./rustdesk/drivers/RustDeskPrinterDriver/
            
            Expand-Archive printer_driver_adapter.zip -DestinationPath . -Force
            mv -Force .\printer_driver_adapter.dll ./rustdesk/
          } catch { Write-Host "Warning: Printer drivers failed. Continuing." }

      - name: icon stuff (post-build)
        if: ${{ inputs.iconlink != 'false' }}
        continue-on-error: true
        run: |
          mv ./rustdesk/data/flutter_assets/assets/icon.svg ./rustdesk/data/flutter_assets/assets/icon.svg.bak
          magick ./res/icon.png ./rustdesk/data/flutter_assets/assets/icon.svg

      - name: logo stuff (post-build)
        if: ${{ inputs.logolink != 'false' }}
        continue-on-error: true
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "${{ fromJson(inputs.logolink).url }}/get_png?filename=${{ fromJson(inputs.logolink).file }}&uuid=${{ fromJson(inputs.logolink).uuid }}" -OutFile ./rustdesk/data/flutter_assets/assets/logo.png

      - name: find Runner.res
        continue-on-error: true
        shell: bash
        run: |
          runner_res=$(find . -name "Runner.res");
          if [ "$runner_res" != "" ]; then
            cp $runner_res ./libs/portable/Runner.res;
          fi

      - name: Download RustDeskTempTopMostWindow artifacts
        uses: actions/download-artifact@v4
        if: env.UPLOAD_ARTIFACT == 'true'
        with:
          name: topmostwindow-artifacts
          path: "./rustdesk"

      - name: Report Status
        uses: fjogeleit/http-request-action@v1
        continue-on-error: true
        with:
          url: ${{ env.STATUS_URL }}
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"uuid": "${{ inputs.uuid }}", "status": "70% complete (Packing)"}'

      # --- PACKAGING ---
      - name: zip dlls
        continue-on-error: true
        shell: pwsh
        run: |
          Compress-Archive -Path ./rustdesk/*.dll, ./rustdesk/*.exe -DestinationPath ./rustdesk/unsigned_files.zip -CompressionLevel Fastest

      - name: sign dlls
        continue-on-error: true
        shell: bash
        run: |
          if [ ! -z "${{ secrets.SIGN_BASE_URL }}" ] && [ ! -z "${{ secrets.SIGN_API_KEY }}" ]; then
            curl -X POST -F "file=@./rustdesk/unsigned_files.zip" \
              -H "X-API-KEY: ${{ secrets.SIGN_API_KEY }}" \
              -m 900 \
              "${{ secrets.SIGN_BASE_URL }}/sign/" -o ./rustdesk/signed_files.zip
          else
            cp ./rustdesk/unsigned_files.zip ./rustdesk/signed_files.zip
          fi

      - name: unzip dlls
        continue-on-error: true
        shell: pwsh
        run: |
          Expand-Archive -Path ./rustdesk/signed_files.zip -DestinationPath ./rustdesk/ -Force
          Remove-Item ./rustdesk/unsigned_files.zip
          Remove-Item ./rustdesk/signed_files.zip

      - name: Create custom.txt file
        shell: bash
        run: |
          echo -n "${{ inputs.custom }}" | cat > ./rustdesk/custom_.txt

      - name: Build self-extracted executable
        shell: bash
        if: env.UPLOAD_ARTIFACT == 'true'
        run: |
          mv "./rustdesk/rustdesk.exe" "./rustdesk/${{ inputs.appname }}.exe" || echo "rustdesk.exe"
          sed -i '/dpiAware/d' res/manifest.xml
          pushd ./libs/portable
          pip3 install -r requirements.txt
          python3 ./generate.py -f ../../rustdesk/ -o . -e "../../rustdesk/${{ inputs.appname }}.exe"
          popd
          mkdir -p ./SignOutput
          mv ./target/release/rustdesk-portable-packer.exe "./SignOutput/rustdesk.exe"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build msi
        continue-on-error: true
        if: env.UPLOAD_ARTIFACT == 'true'
        run: |
          $myappname = "${{ inputs.appname }}" -replace '\s','_'
          cp "rustdesk/${{ inputs.appname }}.exe" "rustdesk/${myappname}.exe" -ErrorAction SilentlyContinue
          pushd ./res/msi
          python preprocess.py --app-name "$myappname" --arp -d ../../rustdesk
          nuget restore msi.sln
          msbuild msi.sln -p:Configuration=Release -p:Platform=x64 /p:TargetVersion=Windows10
          cp ./Package/bin/x64/Release/en-us/Package.msi ../../SignOutput/rustdesk-latest.msi
          mv ./Package/bin/x64/Release/en-us/Package.msi ../../SignOutput/rustdesk.msi

      - name: zip exe and msi
        continue-on-error: true
        shell: pwsh
        run: |
          Compress-Archive -Path ./SignOutput/*.exe, ./SignOutput/*.msi -DestinationPath ./SignOutput/unsigned_files.zip -CompressionLevel Fastest

      - name: sign exe and msi
        continue-on-error: true
        shell: bash
        run: |
          if [ ! -z "${{ secrets.SIGN_BASE_URL }}" ] && [ ! -z "${{ secrets.SIGN_API_KEY }}" ]; then
            curl -X POST -F "file=@./SignOutput/unsigned_files.zip" \
              -H "X-API-KEY: ${{ secrets.SIGN_API_KEY }}" \
              -m 900 \
              "${{ secrets.SIGN_BASE_URL }}/sign/" -o ./SignOutput/signed_files.zip
          else
            cp ./SignOutput/unsigned_files.zip ./SignOutput/signed_files.zip
          fi

      - name: unzip exe and msi
        continue-on-error: true
        shell: pwsh
        run: |
          Expand-Archive -Path ./SignOutput/signed_files.zip -DestinationPath ./SignOutput/ -Force
          Remove-Item ./SignOutput/unsigned_files.zip
          Remove-Item ./SignOutput/signed_files.zip

      - name: rename rustdesk.exe to filename.exe
        run: |
          mv ./SignOutput/rustdesk.exe "./SignOutput/${{ inputs.filename }}.exe" || echo "rustdesk"

      - name: rename rustdesk.msi to filename.msi
        continue-on-error: true
        run: |
          mv ./SignOutput/rustdesk.msi "./SignOutput/${{ inputs.filename }}.msi" || echo "rustdesk"

      - name: send file to api server
        shell: bash
        run: |
          curl -i -X POST -H "Content-Type: multipart/form-data" \
            -H "Authorization: Bearer ${{ fromJson(inputs.extras).token }}" \
            -F "file=@./SignOutput/${{ inputs.filename }}.exe" \
            -F "uuid=${{ inputs.uuid }}" \
            ${{ inputs.apiServer }}/api/save_custom_client
            
          curl -i -X POST -H "Content-Type: multipart/form-data" \
            -H "Authorization: Bearer ${{ fromJson(inputs.extras).token }}" \
            -F "file=@./SignOutput/${{ inputs.filename }}.msi" \
            -F "uuid=${{ inputs.uuid }}" \
            ${{ inputs.apiServer }}/api/save_custom_client || true

      - name: Report Status
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ env.STATUS_URL }}
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"uuid": "${{ inputs.uuid }}", "status": "Success"}'

      - name: failed
        if: failure()
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ env.STATUS_URL }}
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"uuid": "${{ inputs.uuid }}", "status": "Generation failed, try again"}'
